a=open("python.txt","w")
total_no_of_students=int(input("enter="))
total_passed=int(input("enter passed="))
total_failed=int(input("enter failed="))
a.write("\ntotal studens="+str(total_no_of_students))
a.write("\ntotal passed="+str(total_passed))
a.write("\ntotal failed="+str(total_failed))
a=open("python.txt","r")
print(a.read())
a=open("python.txt","a")
average=total_no_of_students+total_passed+total_failed/3
a.write("\naverage="+str(average))
a=open("python.txt","r")
print(a.read())
